services:
  db:
    image: postgres:17-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  social-media-app:
    build:
      context: .
    container_name: social-media-app
    env_file:
      - .env
    depends_on:
      - db
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "7777:8000"
    volumes:
      - ./:/code
