services:
  db:
    image: postgres:17-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env-non-dev

    ports:
      - "5433:5432"


  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"


  social-media-app:
    build:
      context: .
    container_name: social-media-app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "7777:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-social-media-app
    command: celery --app=app.tasks.celery_app:celery worker -l info
    env_file:
      - .env-non-dev
    depends_on:
      - redis